language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10""
install:
  - pip install -r requirements.txt
  - pip install -r maintainers_requirements.txt
script:
  - export PYTHONPATH=`pwd`; cd tests; bash ./rununit.bsh
after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
