
adreg_op_to_method_mapping = {
    "createAdmissionregistrationV1MutatingWebhookConfiguration": "create_mutating_webhook_configuration",
    "deleteAdmissionregistrationV1MutatingWebhookConfiguration": "delete_mutating_webhook_configuration",
    "listAdmissionregistrationV1MutatingWebhookConfiguration": "list_mutating_webhook_configuration",
    "readAdmissionregistrationV1MutatingWebhookConfiguration": "read_mutating_webhook_configuration",
    "replaceAdmissionregistrationV1MutatingWebhookConfiguration": "replace_mutating_webhook_configuration",
    "connect_delete_namespaced_pod_proxy": "deleteCoreV1NamespacedPodProxy",
    "connect_get_namespaced_pod_attach": "getCoreV1NamespacedPodAttach",
    "connect_head_namespaced_service_proxy": "headCoreV1NamespacedServiceProxy",
    "connect_patch_namespaced_node_proxy": "patchCoreV1NamespacedNodeProxy",
    "connect_put_namespaced_service_proxy": "putCoreV1NamespacedServiceProxy",
    "create_namespaced_endpoints": "createCoreV1NamespacedEndpoints",
    "create_namespaced_event": "createCoreV1NamespacedEvent",
    "delete_collection_namespaced_config_map": "deleteCollectionCoreV1NamespacedConfigMap",
    "delete_collection_namespaced_endpoints": "deleteCollectionCoreV1NamespacedEndpoints",
    "delete_namespaced_controller_revision": "deleteCoreV1NamespacedControllerRevision",
    "list_node": "listCoreV1Node",
    "patch_namespaced_endpoints": "patchCoreV1NamespacedEndpoints",
    "read_namespaced_service_status": "readCoreV1NamespacedServiceStatus",
    "replace_namespaced_endpoints": "replaceCoreV1NamespacedEndpoints",
}

core_op_to_method_map = {
    "listCoreV1Pod": "list_namespaced_pod",
    "createCoreV1Namespace": "create_namespace",
    "deleteCoreV1Service": "delete_namespaced_service",
    "getCoreV1Node": "read_node",
    "patchCoreV1ConfigMap": "patch_namespaced_config_map",
    "replaceCoreV1Pod": "replace_namespaced_pod",
    "connect_delete_namespaced_pod_proxy": "deleteCoreV1NamespacedPodProxy",
    "connect_get_namespaced_pod_attach": "getCoreV1NamespacedPodAttach",
    "connect_head_namespaced_service_proxy": "headCoreV1NamespacedServiceProxy",
    "connect_patch_namespaced_node_proxy": "patchCoreV1NamespacedNodeProxy",
    "connect_put_namespaced_service_proxy": "putCoreV1NamespacedServiceProxy",
    "create_namespaced_endpoints": "createCoreV1NamespacedEndpoints",
    "create_namespaced_event": "createCoreV1NamespacedEvent",
    "delete_collection_namespaced_config_map": "deleteCollectionCoreV1NamespacedConfigMap",
    "delete_collection_namespaced_endpoints": "deleteCollectionCoreV1NamespacedEndpoints",
    "delete_namespaced_controller_revision": "deleteCoreV1NamespacedControllerRevision",
    "list_node": "listCoreV1Node",
    "patch_namespaced_endpoints": "patchCoreV1NamespacedEndpoints",
    "read_namespaced_service_status": "readCoreV1NamespacedServiceStatus",
    "replace_namespaced_endpoints": "replaceCoreV1NamespacedEndpoints",
    "readCoreV1NodeStatus": "read_node_status",
    "patchCoreV1NodeStatus": "patch_node_status",
    "replaceCoreV1NodeStatus": "replace_node_status",
    "connectCoreV1PatchNodeProxy": "connect_patch_node_proxy",
    "connectCoreV1PatchNodeProxyWithPath": "connect_patch_node_proxy_with_path"
}

storage_op_to_method_map = {
    "getStorageV1APIResources": "get_api_resources",
    "deleteStorageV1CollectionCSIDriver": "delete_collection_csi_driver",
    "listStorageV1CSIDriver": "list_csi_driver",
    "createStorageV1CSIDriver": "create_csi_driver",
    "deleteStorageV1CSIDriver": "delete_csi_driver",
    "readStorageV1CSIDriver": "read_csi_driver",
    "patchStorageV1CSIDriver": "patch_csi_driver",
    "replaceStorageV1CSIDriver": "replace_csi_driver",
    "deleteStorageV1CollectionCSINode": "delete_collection_csi_node",
    "listStorageV1CSINode": "list_csi_node",
    "createStorageV1CSINode": "create_csi_node",
    "deleteStorageV1CSINode": "delete_csi_node",
    "readStorageV1CSINode": "read_csi_node",
    "patchStorageV1CSINode": "patch_csi_node",
    "replaceStorageV1CSINode": "replace_csi_node",
    "listStorageV1CSIStorageCapacityForAllNamespaces": "list_csi_storage_capacity_for_all_namespaces",
    "deleteStorageV1CollectionNamespacedCSIStorageCapacity": "delete_collection_namespaced_csi_storage_capacity",
    "listStorageV1NamespacedCSIStorageCapacity": "list_namespaced_csi_storage_capacity",
    "createStorageV1NamespacedCSIStorageCapacity": "create_namespaced_csi_storage_capacity",
    "deleteStorageV1NamespacedCSIStorageCapacity": "delete_namespaced_csi_storage_capacity",
    "readStorageV1NamespacedCSIStorageCapacity": "read_namespaced_csi_storage_capacity",
    "patchStorageV1NamespacedCSIStorageCapacity": "patch_namespaced_csi_storage_capacity",
    "replaceStorageV1NamespacedCSIStorageCapacity": "replace_namespaced_csi_storage_capacity",
    "deleteStorageV1CollectionStorageClass": "delete_collection_storage_class",
    "listStorageV1StorageClass": "list_storage_class",
    "createStorageV1StorageClass": "create_storage_class",
    "deleteStorageV1StorageClass": "delete_storage_class",
    "readStorageV1StorageClass": "read_storage_class",
    "patchStorageV1StorageClass": "patch_storage_class",
    "replaceStorageV1StorageClass": "replace_storage_class",
    "deleteStorageV1CollectionVolumeAttachment": "delete_collection_volume_attachment",
    "listStorageV1VolumeAttachment": "list_volume_attachment",
    "createStorageV1VolumeAttachment": "create_volume_attachment",
    "deleteStorageV1VolumeAttachment": "delete_volume_attachment",
    "readStorageV1VolumeAttachment": "read_volume_attachment",
    "patchStorageV1VolumeAttachment": "patch_volume_attachment",
    "replaceStorageV1VolumeAttachment": "replace_volume_attachment",
    "readStorageV1VolumeAttachmentStatus": "read_volume_attachment_status",
    "patchStorageV1VolumeAttachmentStatus": "patch_volume_attachment_status",
    "replaceStorageV1VolumeAttachmentStatus": "replace_volume_attachment_status"
}

policy_op_to_method_map = {
    "getPolicyV1APIResources": "get_api_resources",
    "deletePolicyV1CollectionNamespacedPodDisruptionBudget": "delete_collection_namespaced_pod_disruption_budget",
    "listPolicyV1NamespacedPodDisruptionBudget": "list_namespaced_pod_disruption_budget",
    "createPolicyV1NamespacedPodDisruptionBudget": "create_namespaced_pod_disruption_budget",
    "deletePolicyV1NamespacedPodDisruptionBudget": "delete_namespaced_pod_disruption_budget",
    "readPolicyV1NamespacedPodDisruptionBudget": "read_namespaced_pod_disruption_budget",
    "patchPolicyV1NamespacedPodDisruptionBudget": "patch_namespaced_pod_disruption_budget",
    "replacePolicyV1NamespacedPodDisruptionBudget": "replace_namespaced_pod_disruption_budget",
    "readPolicyV1NamespacedPodDisruptionBudgetStatus": "read_namespaced_pod_disruption_budget_status",
    "patchPolicyV1NamespacedPodDisruptionBudgetStatus": "patch_namespaced_pod_disruption_budget_status",
    "replacePolicyV1NamespacedPodDisruptionBudgetStatus": "replace_namespaced_pod_disruption_budget_status",
    "listPolicyV1PodDisruptionBudgetForAllNamespaces": "list_pod_disruption_budget_for_all_namespaces"
}

rbac_to_method_map = {
    "getRbacAuthorizationV1APIResources": "get_api_resources",
    "deleteRbacAuthorizationV1CollectionClusterRoleBinding": "delete_collection_cluster_role_binding",
    "listRbacAuthorizationV1ClusterRoleBinding": "list_cluster_role_binding",
    "createRbacAuthorizationV1ClusterRoleBinding": "create_cluster_role_binding",
    "deleteRbacAuthorizationV1ClusterRoleBinding": "delete_cluster_role_binding",
    "readRbacAuthorizationV1ClusterRoleBinding": "read_cluster_role_binding",
    "patchRbacAuthorizationV1ClusterRoleBinding": "patch_cluster_role_binding",
    "replaceRbacAuthorizationV1ClusterRoleBinding": "replace_cluster_role_binding",
    "deleteRbacAuthorizationV1CollectionClusterRole": "delete_collection_cluster_role",
    "listRbacAuthorizationV1ClusterRole": "list_cluster_role",
    "createRbacAuthorizationV1ClusterRole": "create_cluster_role",
    "deleteRbacAuthorizationV1ClusterRole": "delete_cluster_role",
    "readRbacAuthorizationV1ClusterRole": "read_cluster_role",
    "patchRbacAuthorizationV1ClusterRole": "patch_cluster_role",
    "replaceRbacAuthorizationV1ClusterRole": "replace_cluster_role",
    "deleteRbacAuthorizationV1CollectionNamespacedRoleBinding": "delete_collection_namespaced_role_binding",
    "listRbacAuthorizationV1NamespacedRoleBinding": "list_namespaced_role_binding",
    "createRbacAuthorizationV1NamespacedRoleBinding": "create_namespaced_role_binding",
    "deleteRbacAuthorizationV1NamespacedRoleBinding": "delete_namespaced_role_binding",
    "readRbacAuthorizationV1NamespacedRoleBinding": "read_namespaced_role_binding",
    "patchRbacAuthorizationV1NamespacedRoleBinding": "patch_namespaced_role_binding",
    "replaceRbacAuthorizationV1NamespacedRoleBinding": "replace_namespaced_role_binding",
    "deleteRbacAuthorizationV1CollectionNamespacedRole": "delete_collection_namespaced_role",
    "listRbacAuthorizationV1NamespacedRole": "list_namespaced_role",
    "createRbacAuthorizationV1NamespacedRole": "create_namespaced_role",
    "deleteRbacAuthorizationV1NamespacedRole": "delete_namespaced_role",
    "readRbacAuthorizationV1NamespacedRole": "read_namespaced_role",
    "patchRbacAuthorizationV1NamespacedRole": "patch_namespaced_role",
    "replaceRbacAuthorizationV1NamespacedRole": "replace_namespaced_role",
    "listRbacAuthorizationV1RoleBindingForAllNamespaces": "list_role_binding_for_all_namespaces",
    "listRbacAuthorizationV1RoleForAllNamespaces": "list_role_for_all_namespaces"
}

adminregv1a1_to_method_map = {
    "getAdmissionregistrationV1alpha1APIResources": "get_api_resources",
    "deleteAdmissionregistrationV1alpha1CollectionValidatingAdmissionPolicy": "delete_collection_validating_admission_policy",
    "listAdmissionregistrationV1alpha1ValidatingAdmissionPolicy": "list_validating_admission_policy",
    "createAdmissionregistrationV1alpha1ValidatingAdmissionPolicy": "create_validating_admission_policy",
    "deleteAdmissionregistrationV1alpha1ValidatingAdmissionPolicy": "delete_validating_admission_policy",
    "readAdmissionregistrationV1alpha1ValidatingAdmissionPolicy": "read_validating_admission_policy",
    "patchAdmissionregistrationV1alpha1ValidatingAdmissionPolicy": "patch_validating_admission_policy",
    "replaceAdmissionregistrationV1alpha1ValidatingAdmissionPolicy": "replace_validating_admission_policy",
    "readAdmissionregistrationV1alpha1ValidatingAdmissionPolicyStatus": "read_validating_admission_policy_status",
    "patchAdmissionregistrationV1alpha1ValidatingAdmissionPolicyStatus": "patch_validating_admission_policy_status",
    "replaceAdmissionregistrationV1alpha1ValidatingAdmissionPolicyStatus": "replace_validating_admission_policy_status",
    "deleteAdmissionregistrationV1alpha1CollectionValidatingAdmissionPolicyBinding": "delete_collection_validating_admission_policy_binding",
    "listAdmissionregistrationV1alpha1ValidatingAdmissionPolicyBinding": "list_validating_admission_policy_binding",
    "createAdmissionregistrationV1alpha1ValidatingAdmissionPolicyBinding": "create_validating_admission_policy_binding",
    "deleteAdmissionregistrationV1alpha1ValidatingAdmissionPolicyBinding": "delete_validating_admission_policy_binding",
    "readAdmissionregistrationV1alpha1ValidatingAdmissionPolicyBinding": "read_validating_admission_policy_binding",
    "patchAdmissionregistrationV1alpha1ValidatingAdmissionPolicyBinding": "patch_validating_admission_policy_binding",
    "replaceAdmissionregistrationV1alpha1ValidatingAdmissionPolicyBinding": "replace_validating_admission_policy_binding"
}

storagev1a1_to_method_map = {
    "getStorageV1alpha1APIResources": "get_api_resources",
    "deleteStorageV1alpha1CollectionVolumeAttributesClass": "delete_collection_volume_attributes_class",
    "listStorageV1alpha1VolumeAttributesClass": "list_volume_attributes_class",
    "createStorageV1alpha1VolumeAttributesClass": "create_volume_attributes_class",
    "deleteStorageV1alpha1VolumeAttributesClass": "delete_volume_attributes_class",
    "readStorageV1alpha1VolumeAttributesClass": "read_volume_attributes_class",
    "patchStorageV1alpha1VolumeAttributesClass": "patch_volume_attributes_class",
    "replaceStorageV1alpha1VolumeAttributesClass": "replace_volume_attributes_class"
}

int_api_to_method_map = {
    "getInternalApiserverV1alpha1APIResources": "get_api_resources",
    "deleteInternalApiserverV1alpha1CollectionStorageVersion": "delete_collection_storage_version",
    "listInternalApiserverV1alpha1StorageVersion": "list_storage_version",
    "createInternalApiserverV1alpha1StorageVersion": "create_storage_version",
    "deleteInternalApiserverV1alpha1StorageVersion": "delete_storage_version",
    "readInternalApiserverV1alpha1StorageVersion": "read_storage_version",
    "patchInternalApiserverV1alpha1StorageVersion": "patch_storage_version",
    "replaceInternalApiserverV1alpha1StorageVersion": "replace_storage_version",
    "readInternalApiserverV1alpha1StorageVersionStatus": "read_storage_version_status",
    "patchInternalApiserverV1alpha1StorageVersionStatus": "patch_storage_version_status",
    "replaceInternalApiserverV1alpha1StorageVersionStatus": "replace_storage_version_status"
}

certsv1a1_to_method_map = {
    "getCertificatesV1alpha1APIResources": "get_api_resources",
    "deleteCertificatesV1alpha1CollectionClusterTrustBundle": "delete_collection_cluster_trust_bundle",
    "listCertificatesV1alpha1ClusterTrustBundle": "list_cluster_trust_bundle",
    "createCertificatesV1alpha1ClusterTrustBundle": "create_cluster_trust_bundle",
    "deleteCertificatesV1alpha1ClusterTrustBundle": "delete_cluster_trust_bundle",
    "readCertificatesV1alpha1ClusterTrustBundle": "read_cluster_trust_bundle",
    "patchCertificatesV1alpha1ClusterTrustBundle": "patch_cluster_trust_bundle",
    "replaceCertificatesV1alpha1ClusterTrustBundle": "replace_cluster_trust_bundle"
}

networkingv1a1_to_method_map = {
    "getNetworkingV1alpha1APIResources": "get_api_resources",
    "deleteNetworkingV1alpha1CollectionIPAddress": "delete_collection_ip_address",
    "listNetworkingV1alpha1IPAddress": "list_ip_address",
    "createNetworkingV1alpha1IPAddress": "create_ip_address",
    "deleteNetworkingV1alpha1IPAddress": "delete_ip_address",
    "readNetworkingV1alpha1IPAddress": "read_ip_address",
    "patchNetworkingV1alpha1IPAddress": "patch_ip_address",
    "replaceNetworkingV1alpha1IPAddress": "replace_ip_address",
    "deleteNetworkingV1alpha1CollectionServiceCIDR": "delete_collection_service_cidr",
    "listNetworkingV1alpha1ServiceCIDR": "list_service_cidr",
    "createNetworkingV1alpha1ServiceCIDR": "create_service_cidr",
    "deleteNetworkingV1alpha1ServiceCIDR": "delete_service_cidr",
    "readNetworkingV1alpha1ServiceCIDR": "read_service_cidr",
    "patchNetworkingV1alpha1ServiceCIDR": "patch_service_cidr",
    "replaceNetworkingV1alpha1ServiceCIDR": "replace_service_cidr",
    "readNetworkingV1alpha1ServiceCIDRStatus": "read_service_cidr_status",
    "patchNetworkingV1alpha1ServiceCIDRStatus": "patch_service_cidr_status",
    "replaceNetworkingV1alpha1ServiceCIDRStatus": "replace_service_cidr_status"
}

adminregv1b1_to_method_map = {
    "getAdmissionregistrationV1beta1APIResources": "get_api_resources",
    "deleteAdmissionregistrationV1beta1CollectionValidatingAdmissionPolicy": "delete_collection_validating_admission_policy",
    "listAdmissionregistrationV1beta1ValidatingAdmissionPolicy": "list_validating_admission_policy",
    "createAdmissionregistrationV1beta1ValidatingAdmissionPolicy": "create_validating_admission_policy",
    "deleteAdmissionregistrationV1beta1ValidatingAdmissionPolicy": "delete_validating_admission_policy",
    "readAdmissionregistrationV1beta1ValidatingAdmissionPolicy": "read_validating_admission_policy",
    "patchAdmissionregistrationV1beta1ValidatingAdmissionPolicy": "patch_validating_admission_policy",
    "replaceAdmissionregistrationV1beta1ValidatingAdmissionPolicy": "replace_validating_admission_policy",
    "readAdmissionregistrationV1beta1ValidatingAdmissionPolicyStatus": "read_validating_admission_policy_status",
    "patchAdmissionregistrationV1beta1ValidatingAdmissionPolicyStatus": "patch_validating_admission_policy_status",
    "replaceAdmissionregistrationV1beta1ValidatingAdmissionPolicyStatus": "replace_validating_admission_policy_status",
    "deleteAdmissionregistrationV1beta1CollectionValidatingAdmissionPolicyBinding": "delete_collection_validating_admission_policy_binding",
    "listAdmissionregistrationV1beta1ValidatingAdmissionPolicyBinding": "list_validating_admission_policy_binding",
    "createAdmissionregistrationV1beta1ValidatingAdmissionPolicyBinding": "create_validating_admission_policy_binding",
    "deleteAdmissionregistrationV1beta1ValidatingAdmissionPolicyBinding": "delete_validating_admission_policy_binding",
    "readAdmissionregistrationV1beta1ValidatingAdmissionPolicyBinding": "read_validating_admission_policy_binding",
    "patchAdmissionregistrationV1beta1ValidatingAdmissionPolicyBinding": "patch_validating_admission_policy_binding",
    "replaceAdmissionregistrationV1beta1ValidatingAdmissionPolicyBinding": "replace_validating_admission_policy_binding"
}

authv1b1_to_method_map = {
    "getAuthenticationV1beta1APIResources": "get_api_resources",
    "createAuthenticationV1beta1SelfSubjectReview": "create_self_subject_review",
    "createAuthenticationV1beta1SelfSubjectReview": "create_self_subject_review"
}

flowcontrov1b3_to_method_map = {
    "getFlowcontrolApiserverV1beta3APIResources": "get_api_resources",
    "deleteFlowcontrolApiserverV1beta3CollectionFlowSchema": "delete_collection_flow_schema",
    "listFlowcontrolApiserverV1beta3FlowSchema": "list_flow_schema",
    "createFlowcontrolApiserverV1beta3FlowSchema": "create_flow_schema",
    "deleteFlowcontrolApiserverV1beta3FlowSchema": "delete_flow_schema",
    "readFlowcontrolApiserverV1beta3FlowSchema": "read_flow_schema",
    "patchFlowcontrolApiserverV1beta3FlowSchema": "patch_flow_schema",
    "replaceFlowcontrolApiserverV1beta3FlowSchema": "replace_flow_schema",
    "readFlowcontrolApiserverV1beta3FlowSchemaStatus": "read_flow_schema_status",
    "patchFlowcontrolApiserverV1beta3FlowSchemaStatus": "patch_flow_schema_status",
    "replaceFlowcontrolApiserverV1beta3FlowSchemaStatus": "replace_flow_schema_status",
    "deleteFlowcontrolApiserverV1beta3CollectionPriorityLevelConfiguration": "delete_collection_priority_level_configuration",
    "listFlowcontrolApiserverV1beta3PriorityLevelConfiguration": "list_priority_level_configuration",
    "createFlowcontrolApiserverV1beta3PriorityLevelConfiguration": "create_priority_level_configuration",
    "deleteFlowcontrolApiserverV1beta3PriorityLevelConfiguration": "delete_priority_level_configuration",
    "readFlowcontrolApiserverV1beta3PriorityLevelConfiguration": "read_priority_level_configuration",
    "patchFlowcontrolApiserverV1beta3PriorityLevelConfiguration": "patch_priority_level_configuration",
    "replaceFlowcontrolApiserverV1beta3PriorityLevelConfiguration": "replace_priority_level_configuration",
    "readFlowcontrolApiserverV1beta3PriorityLevelConfigurationStatus": "read_priority_level_configuration_status",
    "patchFlowcontrolApiserverV1beta3PriorityLevelConfigurationStatus": "patch_priority_level_configuration_status",
    "replaceFlowcontrolApiserverV1beta3PriorityLevelConfigurationStatus": "replace_priority_level_configuration_status"
}

authv1a1_to_method_map = {
    "getAuthenticationV1alpha1APIResources": "get_api_resources",
    "createAuthenticationV1alpha1SelfSubjectReview": "create_self_subject_review"
}

networkingv1_to_method_map = {
    "listNetworkingV1NetworkPolicyForAllNamespaces": "list_network_policy_for_all_namespaces",
}

appsApiv1_to_method_map = {
    "listAppsV1ControllerRevisionForAllNamespaces": "list_controller_revision_for_all_namespaces",
    "listAppsV1DaemonSetForAllNamespaces": "list_daemon_set_for_all_namespaces",
    "listAppsV1DeploymentForAllNamespaces": "list_deployment_for_all_namespaces",
    "deleteAppsV1CollectionNamespacedControllerRevision": "delete_collection_namespaced_controller_revision",
    "listAppsV1NamespacedControllerRevision": "list_namespaced_controller_revision",
    "createAppsV1NamespacedControllerRevision": "create_namespaced_controller_revision",
    "deleteAppsV1NamespacedControllerRevision": "delete_namespaced_controller_revision",
    "readAppsV1NamespacedControllerRevision": "read_namespaced_controller_revision",
    "patchAppsV1NamespacedControllerRevision": "patch_namespaced_controller_revision",
    "replaceAppsV1NamespacedControllerRevision": "replace_namespaced_controller_revision",
    "deleteAppsV1CollectionNamespacedDaemonSet": "delete_collection_namespaced_daemon_set",
    "listAppsV1NamespacedDaemonSet": "list_namespaced_daemon_set",
    "createAppsV1NamespacedDaemonSet": "create_namespaced_daemon_set",
    "deleteAppsV1NamespacedDaemonSet": "delete_namespaced_daemon_set",
    "readAppsV1NamespacedDaemonSet": "read_namespaced_daemon_set",
    "patchAppsV1NamespacedDaemonSet": "patch_namespaced_daemon_set",
    "replaceAppsV1NamespacedDaemonSet": "replace_namespaced_daemon_set",
    "readAppsV1NamespacedDaemonSetStatus": "read_namespaced_daemon_set_status",
    "patchAppsV1NamespacedDaemonSetStatus": "patch_namespaced_daemon_set_status",
    "replaceAppsV1NamespacedDaemonSetStatus": "replace_namespaced_daemon_set_status",
    "deleteAppsV1CollectionNamespacedDeployment": "delete_collection_namespaced_deployment",
    "listAppsV1NamespacedDeployment": "list_namespaced_deployment",
    "createAppsV1NamespacedDeployment": "create_namespaced_deployment",
    "deleteAppsV1NamespacedDeployment": "delete_namespaced_deployment",
    "readAppsV1NamespacedDeployment": "read_namespaced_deployment",
    "patchAppsV1NamespacedDeployment": "patch_namespaced_deployment",
    "replaceAppsV1NamespacedDeployment": "replace_namespaced_deployment",
    "readAppsV1NamespacedDeploymentScale": "read_namespaced_deployment_scale",
    "patchAppsV1NamespacedDeploymentScale": "patch_namespaced_deployment_scale",
    "replaceAppsV1NamespacedDeploymentScale": "replace_namespaced_deployment_scale",
    "readAppsV1NamespacedDeploymentStatus": "read_namespaced_deployment_status",
    "patchAppsV1NamespacedDeploymentStatus": "patch_namespaced_deployment_status",
    "replaceAppsV1NamespacedDeploymentStatus": "replace_namespaced_deployment_status",
    "deleteAppsV1CollectionNamespacedReplicaSet": "delete_collection_namespaced_replica_set",
    "listAppsV1NamespacedReplicaSet": "list_namespaced_replica_set",
    "createAppsV1NamespacedReplicaSet": "create_namespaced_replica_set",
    "deleteAppsV1NamespacedReplicaSet": "delete_namespaced_replica_set",
    "readAppsV1NamespacedReplicaSet": "read_namespaced_replica_set",
    "patchAppsV1NamespacedReplicaSet": "patch_namespaced_replica_set",
    "replaceAppsV1NamespacedReplicaSet": "replace_namespaced_replica_set",
    "readAppsV1NamespacedReplicaSetScale": "read_namespaced_replica_set_scale",
    "patchAppsV1NamespacedReplicaSetScale": "patch_namespaced_replica_set_scale",
    "replaceAppsV1NamespacedReplicaSetScale": "replace_namespaced_replica_set_scale",
    "readAppsV1NamespacedReplicaSetStatus": "read_namespaced_replica_set_status",
    "patchAppsV1NamespacedReplicaSetStatus": "patch_namespaced_replica_set_status",
    "replaceAppsV1NamespacedReplicaSetStatus": "replace_namespaced_replica_set_status",
    "deleteAppsV1CollectionNamespacedStatefulSet": "delete_collection_namespaced_stateful_set",
    "listAppsV1NamespacedStatefulSet": "list_namespaced_stateful_set",
    "createAppsV1NamespacedStatefulSet": "create_namespaced_stateful_set",
    "deleteAppsV1NamespacedStatefulSet": "delete_namespaced_stateful_set",
    "readAppsV1NamespacedStatefulSet": "read_namespaced_stateful_set",
    "patchAppsV1NamespacedStatefulSet": "patch_namespaced_stateful_set",
    "replaceAppsV1NamespacedStatefulSet": "replace_namespaced_stateful_set",
    "readAppsV1NamespacedStatefulSetScale": "read_namespaced_stateful_set_scale",
    "patchAppsV1NamespacedStatefulSetScale": "patch_namespaced_stateful_set_scale",
    "replaceAppsV1NamespacedStatefulSetScale": "replace_namespaced_stateful_set_scale",
    "readAppsV1NamespacedStatefulSetStatus": "read_namespaced_stateful_set_status",
    "patchAppsV1NamespacedStatefulSetStatus": "patch_namespaced_stateful_set_status",
    "replaceAppsV1NamespacedStatefulSetStatus": "replace_namespaced_stateful_set_status",
    "listAppsV1ReplicaSetForAllNamespaces": "list_replica_set_for_all_namespaces",
    "listAppsV1StatefulSetForAllNamespaces": "list_stateful_set_for_all_namespaces",
    "getAppsV1APIResources": "get_api_resources"
}

autoscalingv1_to_method_map = {
    "getAutoscalingV1APIResources": "get_api_resources",
    "listAutoscalingV1HorizontalPodAutoscalerForAllNamespaces": "list_horizontal_pod_autoscaler_for_all_namespaces",
    "deleteAutoscalingV1CollectionNamespacedHorizontalPodAutoscaler": "delete_collection_namespaced_horizontal_pod_autoscaler",
    "listAutoscalingV1NamespacedHorizontalPodAutoscaler": "list_namespaced_horizontal_pod_autoscaler",
    "createAutoscalingV1NamespacedHorizontalPodAutoscaler": "create_namespaced_horizontal_pod_autoscaler",
    "deleteAutoscalingV1NamespacedHorizontalPodAutoscaler": "delete_namespaced_horizontal_pod_autoscaler",
    "readAutoscalingV1NamespacedHorizontalPodAutoscaler": "read_namespaced_horizontal_pod_autoscaler",
    "patchAutoscalingV1NamespacedHorizontalPodAutoscaler": "patch_namespaced_horizontal_pod_autoscaler",
    "replaceAutoscalingV1NamespacedHorizontalPodAutoscaler": "replace_namespaced_horizontal_pod_autoscaler",
    "readAutoscalingV1NamespacedHorizontalPodAutoscalerStatus": "read_namespaced_horizontal_pod_autoscaler_status"
}

flowcontrolapiv1_to_method = {
    "patchFlowcontrolApiserverV1FlowSchema": "patch_flow_schema",
    "listFlowcontrolApiserverV1PriorityLevelConfiguration": "list_priority_level_configuration",
    "replaceFlowcontrolApiserverV1FlowSchemaStatus": "replace_flow_schema_status",
    "patchFlowcontrolApiserverV1PriorityLevelConfigurationStatus": "patch_priority_level_configuration_status",
    "deleteFlowcontrolApiserverV1CollectionFlowSchema": "delete_collection_flow_schema",
    "readFlowcontrolApiserverV1PriorityLevelConfiguration": "read_priority_level_configuration",
    "listFlowcontrolApiserverV1FlowSchema": "list_flow_schema",
    "createFlowcontrolApiserverV1PriorityLevelConfiguration": "create_priority_level_configuration",
    "readFlowcontrolApiserverV1FlowSchema": "read_flow_schema",
    "readFlowcontrolApiserverV1FlowSchemaStatus": "read_flow_schema_status",
    "deleteFlowcontrolApiserverV1CollectionPriorityLevelConfiguration": "delete_collection_priority_level_configuration",
    "deleteFlowcontrolApiserverV1FlowSchema": "delete_flow_schema",
    "patchFlowcontrolApiserverV1FlowSchemaStatus": "patch_flow_schema_status",
    "deleteFlowcontrolApiserverV1PriorityLevelConfiguration": "delete_priority_level_configuration",
    "replaceFlowcontrolApiserverV1PriorityLevelConfigurationStatus": "replace_priority_level_configuration_status",
    "patchFlowcontrolApiserverV1PriorityLevelConfiguration": "patch_priority_level_configuration",
    "replaceFlowcontrolApiserverV1FlowSchema": "replace_flow_schema",
    "createFlowcontrolApiserverV1FlowSchema": "create_flow_schema",
    "replaceFlowcontrolApiserverV1PriorityLevelConfiguration": "replace_priority_level_configuration",
    "readFlowcontrolApiserverV1PriorityLevelConfigurationStatus": "read_priority_level_configuration_status",
    "getFlowcontrolApiserverV1APIResources": "get_api_resources",
}



# _custom_method_name_builders
all_mappers = {
    "AdmissionregistrationV1Api": adreg_op_to_method_mapping,
    "AppsV1Api": appsApiv1_to_method_map,
    "AutoscalingV1Api": autoscalingv1_to_method_map,
    "CoreV1Api": core_op_to_method_map,
    "FlowcontrolApiserverV1Api": flowcontrolapiv1_to_method,
    "StorageV1Api": storage_op_to_method_map,
    "PolicyV1Api": policy_op_to_method_map,
    "RbacAuthorizationV1Api": rbac_to_method_map,
    "AdmissionregistrationV1alpha1Api": adminregv1a1_to_method_map,
    "StorageV1alpha1Api": storagev1a1_to_method_map,
    "InternalApiserverV1alpha1Api": int_api_to_method_map,
    "AuthenticationV1alpha1Api": authv1a1_to_method_map,
    "CertificatesV1alpha1Api": certsv1a1_to_method_map,
    "NetworkingV1alpha1Api": networkingv1a1_to_method_map,
    "AdmissionregistrationV1beta1Api": adminregv1b1_to_method_map,
    "AuthenticationV1beta1Api": authv1b1_to_method_map,
    "FlowcontrolApiserverV1beta3Api": flowcontrov1b3_to_method_map,
    "NetworkingV1Api": networkingv1_to_method_map
}
