#
# Copyright (c) 2021 Incisive Technology Ltd
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
"""
DO NOT EDIT THIS FILE!

This module is automatically generated using the Hikaru build program that turns
a Kubernetes swagger spec into the code for the hikaru.model package.
"""

from .v1 import *


class Watchables(object):  # pragma: no cover
    """
    Attributes of this class are classes that support watches without the namespace
    keyword argument
    """
    MutatingWebhookConfiguration = MutatingWebhookConfiguration
    MutatingWebhookConfigurationList = MutatingWebhookConfigurationList
    ValidatingWebhookConfiguration = ValidatingWebhookConfiguration
    ValidatingWebhookConfigurationList = ValidatingWebhookConfigurationList
    ControllerRevision = ControllerRevision
    ControllerRevisionList = ControllerRevisionList
    DaemonSetList = DaemonSetList
    DaemonSet = DaemonSet
    Deployment = Deployment
    DeploymentList = DeploymentList
    ReplicaSet = ReplicaSet
    ReplicaSetList = ReplicaSetList
    StatefulSet = StatefulSet
    StatefulSetList = StatefulSetList
    HorizontalPodAutoscaler = HorizontalPodAutoscaler
    HorizontalPodAutoscalerList = HorizontalPodAutoscalerList
    CronJobList = CronJobList
    CronJob = CronJob
    JobList = JobList
    Job = Job
    CertificateSigningRequest = CertificateSigningRequest
    CertificateSigningRequestList = CertificateSigningRequestList
    LeaseList = LeaseList
    Lease = Lease
    ComponentStatusList = ComponentStatusList
    ComponentStatus = ComponentStatus
    ConfigMapList = ConfigMapList
    ConfigMap = ConfigMap
    EndpointsList = EndpointsList
    Endpoints = Endpoints
    EventList = EventList
    Event = Event
    LimitRange = LimitRange
    LimitRangeList = LimitRangeList
    NamespaceList = NamespaceList
    Namespace = Namespace
    NodeList = NodeList
    Node = Node
    PersistentVolume = PersistentVolume
    PersistentVolumeClaim = PersistentVolumeClaim
    PersistentVolumeClaimList = PersistentVolumeClaimList
    PersistentVolumeList = PersistentVolumeList
    PodList = PodList
    Pod = Pod
    PodTemplate = PodTemplate
    PodTemplateList = PodTemplateList
    ReplicationController = ReplicationController
    ReplicationControllerList = ReplicationControllerList
    ResourceQuota = ResourceQuota
    ResourceQuotaList = ResourceQuotaList
    SecretList = SecretList
    Secret = Secret
    ServiceAccount = ServiceAccount
    ServiceAccountList = ServiceAccountList
    ServiceList = ServiceList
    Service = Service
    EndpointSlice = EndpointSlice
    EndpointSliceList = EndpointSliceList
    FlowSchema = FlowSchema
    FlowSchemaList = FlowSchemaList
    PriorityLevelConfiguration = PriorityLevelConfiguration
    PriorityLevelConfigurationList = PriorityLevelConfigurationList
    IngressClass = IngressClass
    IngressClassList = IngressClassList
    IngressList = IngressList
    Ingress = Ingress
    NetworkPolicy = NetworkPolicy
    NetworkPolicyList = NetworkPolicyList
    RuntimeClass = RuntimeClass
    RuntimeClassList = RuntimeClassList
    PodDisruptionBudget = PodDisruptionBudget
    PodDisruptionBudgetList = PodDisruptionBudgetList
    ClusterRole = ClusterRole
    ClusterRoleBinding = ClusterRoleBinding
    ClusterRoleBindingList = ClusterRoleBindingList
    ClusterRoleList = ClusterRoleList
    RoleBinding = RoleBinding
    RoleBindingList = RoleBindingList
    RoleList = RoleList
    Role = Role
    PriorityClass = PriorityClass
    PriorityClassList = PriorityClassList
    CSIDriverList = CSIDriverList
    CSIDriver = CSIDriver
    CSINodeList = CSINodeList
    CSINode = CSINode
    CSIStorageCapacity = CSIStorageCapacity
    CSIStorageCapacityList = CSIStorageCapacityList
    StorageClass = StorageClass
    StorageClassList = StorageClassList
    VolumeAttachment = VolumeAttachment
    VolumeAttachmentList = VolumeAttachmentList
    CustomResourceDefinition = CustomResourceDefinition
    CustomResourceDefinitionList = CustomResourceDefinitionList
    APIService = APIService
    APIServiceList = APIServiceList


watchables = Watchables


class NamespacedWatchables(object):  # pragma: no cover
    """
    Attributes of this class are classes that support watches with the namespace
    keyword argument
    """
    ControllerRevisionList = ControllerRevisionList
    DaemonSetList = DaemonSetList
    DeploymentList = DeploymentList
    ReplicaSetList = ReplicaSetList
    StatefulSetList = StatefulSetList
    HorizontalPodAutoscalerList = HorizontalPodAutoscalerList
    CronJobList = CronJobList
    JobList = JobList
    LeaseList = LeaseList
    ConfigMapList = ConfigMapList
    EndpointsList = EndpointsList
    EventList = EventList
    LimitRangeList = LimitRangeList
    PersistentVolumeClaimList = PersistentVolumeClaimList
    PodList = PodList
    PodTemplateList = PodTemplateList
    ReplicationControllerList = ReplicationControllerList
    ResourceQuotaList = ResourceQuotaList
    SecretList = SecretList
    ServiceAccountList = ServiceAccountList
    ServiceList = ServiceList
    EndpointSliceList = EndpointSliceList
    IngressList = IngressList
    NetworkPolicyList = NetworkPolicyList
    PodDisruptionBudgetList = PodDisruptionBudgetList
    RoleBindingList = RoleBindingList
    RoleList = RoleList
    CSIStorageCapacityList = CSIStorageCapacityList
    ControllerRevision = ControllerRevision
    DaemonSet = DaemonSet
    Deployment = Deployment
    ReplicaSet = ReplicaSet
    StatefulSet = StatefulSet
    HorizontalPodAutoscaler = HorizontalPodAutoscaler
    CronJob = CronJob
    Job = Job
    Lease = Lease
    ConfigMap = ConfigMap
    Endpoints = Endpoints
    Event = Event
    LimitRange = LimitRange
    PersistentVolumeClaim = PersistentVolumeClaim
    Pod = Pod
    PodTemplate = PodTemplate
    ReplicationController = ReplicationController
    ResourceQuota = ResourceQuota
    Secret = Secret
    ServiceAccount = ServiceAccount
    Service = Service
    EndpointSlice = EndpointSlice
    Ingress = Ingress
    NetworkPolicy = NetworkPolicy
    PodDisruptionBudget = PodDisruptionBudget
    RoleBinding = RoleBinding
    Role = Role
    CSIStorageCapacity = CSIStorageCapacity


namespaced_watchables = NamespacedWatchables
